
overrides:
  ceph:
    log-whitelist:
      - responding to mclientcaps\(revoke\)
      - not advance its oldest_client_tid
      - failing to advance its oldest client/flush tid
      - Too many inodes in cache
      - failing to respond to cache pressure
      - slow requests are blocked
      - failing to respond to capability release

tasks:
  - cephfs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.cephfs.test_client_limits
